# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken

    google:
        enabled: true
        server_name: GSB       # Server name used in QR code
        issuer: GSB            # Issuer name used in QR code
        leeway: 15                      # Acceptable time drift in seconds, must be less or equal than 30 seconds


